name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use the Node.js version your project requires
          cache: 'npm'       # optional: speeds up installs by caching dependencies

      - name: Install dependencies
        run:  npm ci      # Use npm ci for a clean, reproducible install (recommended for CI/CD)


      - name: Build the app
        run : npm run build